(let ((path (arg "PATH_INFO"))
      (q (param "q")))
  (let ((hello (re2fullgroups "^/hello/(?<name>[^/]+)$" path)))
    (let ((route
            (if (streq "/" path)
              "root"
              (if (is-empty hello)
                (if (streq "/form" path) "form" "missing")
                "hello"))))
      (if (streq "root" route)
        (let ()
          (write "Status: 200 OK\r\n")
          (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
          (write "<!doctype html><h1>Thue++ Lisp web</h1><p>raw explicit routes</p>"))
        (if (streq "hello" route)
          (let ()
            (write "Status: 200 OK\r\n")
            (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
            (write "<!doctype html><p>Hello, ")
            (write (escape-html (get hello (quote name) "")))
            (write "</p>"))
          (if (streq "form" route)
            (let ()
              (write "Status: 200 OK\r\n")
              (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
              (write "<!doctype html><form method=post><input name=q value=\"")
              (write (escape-html q))
              (write "\"><button>Send</button></form><pre>")
              (write (escape-html q))
              (write "</pre>"))
            (let ()
              (write "Status: 404 Not Found\r\n")
              (write "Content-Type: text/plain; charset=utf-8\r\n\r\n")
              (write "not found"))))))))
