(let ((path (arg "PATH_INFO")))
  (if (streq "/" path)
    (let ()
      (write "Status: 200 OK\r\n")
      (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
      (write "<!doctype html><style>body{max-width:42rem;margin:3rem auto;padding:0 1rem;font:16px/1.5 system-ui,sans-serif;background:#f8fafc;color:#111827}main{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:1.5rem}a{color:#2563eb}</style><main><h1>Thue++ Lisp CGI demo</h1><p>A tiny wrapper-free Lisp CGI app with explicit routes.</p><p><a href=\"/cgi-bin/web-demo.cgi/form\">Try the name form</a></p><p><a href=\"/cgi-bin/web-demo.cgi/hello/Ada\">Hello route example</a></p></main>"))
    (if (streq "/form" path)
      (let ((method (arg "REQUEST_METHOD")))
        (if (streq "POST" method)
          (let ((name (param "name")))
            (if (re2full "^[A-Za-z0-9_.-]+$" name)
              (let ()
                (write "Status: 200 OK\r\n")
                (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
                (write "<!doctype html><style>body{max-width:42rem;margin:3rem auto;padding:0 1rem;font:16px/1.5 system-ui,sans-serif;background:#f8fafc;color:#111827}main{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:1.5rem}input,button{font:inherit;padding:.5rem .7rem;border-radius:8px;border:1px solid #d1d5db}button{background:#111827;color:white;border-color:#111827}a{color:#2563eb}</style><main><h1>Thue++ Lisp CGI demo</h1><p>Hello, ")
                (write (escape-html name))
                (write "!</p><p>Permanent URL: <a href=\"/cgi-bin/web-demo.cgi/hello/")
                (write name)
                (write "\">/hello/")
                (write (escape-html name))
                (write "</a></p><form method=post><label>What is your name? <input name=name value=\"")
                (write (escape-html name))
                (write "\"></label> <button>Say hello</button></form></main>"))
              (let ()
                (write "Status: 200 OK\r\n")
                (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
                (write "<!doctype html><style>body{max-width:42rem;margin:3rem auto;padding:0 1rem;font:16px/1.5 system-ui,sans-serif;background:#f8fafc;color:#111827}main{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:1.5rem}input,button{font:inherit;padding:.5rem .7rem;border-radius:8px;border:1px solid #d1d5db}button{background:#111827;color:white;border-color:#111827}[role=alert]{color:#b91c1c}</style><main><h1>Thue++ Lisp CGI demo</h1><p role=alert>Use only letters, numbers, underscore, dot, or dash.</p><form method=post><label>What is your name? <input name=name value=\"")
                (write (escape-html name))
                (write "\"></label> <button>Say hello</button></form></main>"))))
          (let ()
            (write "Status: 200 OK\r\n")
            (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
            (write "<!doctype html><style>body{max-width:42rem;margin:3rem auto;padding:0 1rem;font:16px/1.5 system-ui,sans-serif;background:#f8fafc;color:#111827}main{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:1.5rem}input,button{font:inherit;padding:.5rem .7rem;border-radius:8px;border:1px solid #d1d5db}button{background:#111827;color:white;border-color:#111827}</style><main><h1>Thue++ Lisp CGI demo</h1><form method=post><label>What is your name? <input name=name value=\"\"></label> <button>Say hello</button></form></main>"))))
      (let ((hello (re2fullgroups "^/hello/(?<name>[^/]+)$" path)))
        (if (is-empty hello)
          (let ()
            (write "Status: 404 Not Found\r\n")
            (write "Content-Type: text/plain; charset=utf-8\r\n\r\n")
            (write "not found"))
          (let ()
            (write "Status: 200 OK\r\n")
            (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
            (write "<!doctype html><style>body{max-width:42rem;margin:3rem auto;padding:0 1rem;font:16px/1.5 system-ui,sans-serif;background:#f8fafc;color:#111827}main{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:1.5rem}a{color:#2563eb}</style><main><p>Hello, ")
            (write (escape-html (get hello (quote name) "")))
            (write "!</p><p><a href=\"/cgi-bin/web-demo.cgi/form\">Back to form</a></p></main>")))))))
