(write "Content-Type: text/html\r\n\r\n")
(write "<!doctype html><meta charset=utf-8>")
(write "<form method=post>")
(write "<input name=q value=\"")
(write (escape-html (param "q")))
(write "\"><button>Send</button></form>")
(write "<pre>")
(write (escape-html (param "q")))
(write "</pre>")
