(let ((method (arg "REQUEST_METHOD"))
      (path (arg "PATH_INFO"))
      (q (param "q")))
  (if (and (streq "GET" method) (streq "/" path))
    (let ()
      (write "Status: 200 OK\r\n")
      (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
      (write "<!doctype html><h1>Thue++ Lisp web</h1><p>raw explicit routes</p>"))
    (if (and (streq "GET" method) (re2full "^/hello/[^/]+$" path))
      (let ((groups (re2fullgroups "^/hello/(?<name>[^/]+)$" path)))
        (write "Status: 200 OK\r\n")
        (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
        (write "<!doctype html><p>Hello, ")
        (write (escape-html (frame-get groups "name")))
        (write "</p>"))
      (if (and (or (streq "GET" method) (streq "POST" method)) (streq "/form" path))
        (let ()
          (write "Status: 200 OK\r\n")
          (write "Content-Type: text/html; charset=utf-8\r\n\r\n")
          (write "<!doctype html><form method=post><input name=q value=\"")
          (write (escape-html q))
          (write "\"><button>Send</button></form><pre>")
          (write (escape-html q))
          (write "</pre>"))
        (let ()
          (write "Status: 404 Not Found\r\n")
          (write "Content-Type: text/plain; charset=utf-8\r\n\r\n")
          (write "not found"))))))
